trigger:
- ci

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  displayName: "Setup"
  inputs:
    versionSpec: '12.x'
- script: 'npm install'
  displayName: "Instala dependências"

- script: "npm run cy:run-junit"
  displayName: "Executa os testes"
  
- task: PublishTestResults@2
  displayName: "Gera o Relatório"
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/*.xml'